In [3]:
import numpy as np

## DataType & Attributes

In [4]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([
    [1,2.0,3.3],
    [4,5,6.4]
])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.4]])

In [7]:
a3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [8]:
# shape of an array: the number of elements in each dimension
# 1-dimension 
# Names: Array, Vector 
# Result (vector,) => (number_of_rows, number_columns)

# The difference between (R,) and (1,R) is literally the number of indices that you need to use. ones((1,R)) is a 2-D array 
# that happens to have only one row. ones(R) is a vector. Generally if it doesn't make sense for the variable to have more 
# than one row/column, you should be using a vector, not a matrix with a singleton dimension.

a1.shape

(3,)

In [9]:
# 2-dimension
# Name: Array, matrix
# Result => (number_of_rows, number_columns)
a2.shape

(2, 3)

In [10]:
# 3-dimension, n-dimension
# Name: Array, matrix
# Result => (n_dimension, number_of_rows_of_each_array, number_of_cols_of_each_array)
# axis = 0 (rows), axis = 1 (columns), axis = n (dimension)
a3.shape

(3, 2, 3)

In [11]:
# number of dimension
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# create a dataframe from a numpy array
import pandas as pd

In [16]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.4

# Creating arrays

In [20]:
sample_arr = np.array([1,2,3])
sample_arr

array([1, 2, 3])

In [22]:
sample_arr.dtype

dtype('int32')

In [23]:
# shift + tab => help
# return a new array of given shape and type, filled with ones
ones = np.ones((2,3))

In [24]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
ones.dtype

dtype('float64')

In [27]:
type(ones)

numpy.ndarray

In [28]:
# return a new array of given shape and type, filled with zeroes
zeros = np.zeros((2,3))

In [29]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
range_arr = np.arange(0,10,2)
range_arr

array([0, 2, 4, 6, 8])

In [32]:
# return random integers from low to high, size
random_arr = np.random.randint(0,10,size=(3,5))
random_arr

array([[4, 3, 9, 7, 1],
       [1, 0, 4, 5, 9],
       [4, 3, 7, 8, 0]])

In [33]:
random_arr.size

15

In [34]:
random_arr.shape

(3, 5)

In [37]:
# return random floats in the half-open interval [0.0, 1.0]
random_arr2 = np.random.random((5,3))
random_arr2

array([[0.25905889, 0.3426937 , 0.45426103],
       [0.47039661, 0.64206115, 0.48436394],
       [0.62305215, 0.29490238, 0.86817245],
       [0.31818983, 0.59140277, 0.33145027],
       [0.78997978, 0.19727001, 0.60104456]])

In [38]:
random_arr2.shape

(5, 3)

In [39]:
random_arr3 = np.random.rand(5,3)
random_arr3

array([[0.79763036, 0.61999641, 0.13384507],
       [0.51051393, 0.33604284, 0.75527477],
       [0.33071677, 0.5953852 , 0.24192483],
       [0.54685769, 0.34359256, 0.07097781],
       [0.80237426, 0.82700527, 0.09199011]])

In [45]:
# Pseudo-random numbers: 
# whenever we run this function without numpy seed being run, what it's actually
# doing is setting the seed to be something random every single time you run this
# But if we set our seed manually, we're going to get the same random numbers back
# Main purpose of using  random seed is if we wanted someone else to be able to
# use our notebook and generate random numbers but the same random numbers as us
# and thus reproduce our experment

# seed: number is still same random to me, not change if re-run the code
np.random.seed(seed=0)
random_arr4 = np.random.randint(10, size=(5,3))
random_arr4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [44]:
random_arr4.shape

(5, 3)

In [49]:
np.random.seed(seed=7)
# seed: number is still same random to me, not change if re-run the code
# generate some random numbers, but if you see the random scene and it's set
# to 7, make sure they're same every time the random
random_arr5 = np.random.random((5,3))
random_arr5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

# Viewing arrays and matrices

In [51]:
np.unique(random_arr4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a1

array([1, 2, 3])

In [53]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.4]])

In [54]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [55]:
a1[0]

1

In [56]:
a2[0]

array([1. , 2. , 3.3])

In [57]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a2[1]

array([4. , 5. , 6.4])

In [59]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [60]:
a4 = np.random.randint(10, size=(2,3,4,5))

In [61]:
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [62]:
a4.shape

(2, 3, 4, 5)

In [63]:
a4.ndim

4

In [64]:
# get the first 4 numbers of the inner most array
a4[:,:,:,:4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

In [68]:
a4[:,:,:,:1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])