# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([
    [1,2.0,3.3],
    [4,5,6.4]
])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.4]])

In [5]:
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [7]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [8]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 2, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

In [11]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,3,2))
zeros

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3
range_arr = np.arange(0,100,3)
range_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_arr = np.random.randint(0,10,size=(7,2))
random_arr

array([[2, 5],
       [9, 4],
       [0, 8],
       [3, 1],
       [1, 7],
       [1, 0],
       [4, 5]])

In [16]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_arr2 = np.random.random((3,5))
random_arr2

array([[0.61228042, 0.21114205, 0.47035372, 0.65058221, 0.20544396],
       [0.76358158, 0.04376133, 0.85615217, 0.07268859, 0.18349089],
       [0.65387235, 0.80069809, 0.35870391, 0.97666773, 0.55323715]])

In [21]:
# Set the random seed to 42
np.random.seed(42)

In [23]:
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_arr3 = np.random.randint(0,10,size=(4,6))
random_arr3

array([[8, 0, 9, 2, 6, 3],
       [8, 2, 4, 2, 6, 4],
       [8, 6, 1, 3, 8, 1],
       [9, 8, 9, 4, 1, 3]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [24]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_arr4 = np.random.randint(0,10,size=(4,6))
random_arr4

array([[6, 7, 2, 0, 3, 1],
       [7, 3, 1, 5, 5, 9],
       [3, 5, 1, 9, 1, 9],
       [3, 7, 6, 8, 7, 4]])

In [25]:
# Find the unique numbers in the array you just created
np.unique(random_arr4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Find the 0'th index of the latest array you created
random_arr4[0]

array([6, 7, 2, 0, 3, 1])

In [28]:
# Get the first 2 rows of latest array you created
random_arr4[:2]

array([[6, 7, 2, 0, 3, 1],
       [7, 3, 1, 5, 5, 9]])

In [29]:
# Get the first 2 values of the first 2 rows of the latest array
random_arr4[:2,:2]

array([[6, 7],
       [7, 3]])

In [31]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_arr5 = np.random.randint(0,10, size=(3,5))
random_arr5

array([[4, 7, 9, 8, 8],
       [0, 8, 6, 8, 7],
       [0, 7, 7, 2, 0]])

In [32]:
ones_arr = np.ones((3,5))
ones_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
# Add the two arrays together
add_arr = random_arr5 + ones_arr
add_arr

array([[ 5.,  8., 10.,  9.,  9.],
       [ 1.,  9.,  7.,  9.,  8.],
       [ 1.,  8.,  8.,  3.,  1.]])

In [36]:
# Create another array of ones of shape (5, 3)
ones_arr1 = np.ones((5,3))
ones_arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
# Try add the array of ones and the other most recent array together
add_arr + ones_arr1

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [38]:
# Create another array of ones of shape (3, 5)
ones_arr2 = np.ones((3,5))
ones_arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
# Subtract the new array of ones from the other most recent array
ones_arr2 - add_arr

array([[-4., -7., -9., -8., -8.],
       [ 0., -8., -6., -8., -7.],
       [ 0., -7., -7., -2.,  0.]])

In [41]:
# Multiply the ones array with the latest array
ones_arr2 * add_arr

array([[ 5.,  8., 10.,  9.,  9.],
       [ 1.,  9.,  7.,  9.,  8.],
       [ 1.,  8.,  8.,  3.,  1.]])

In [44]:
# Take the latest array to the power of 2 using '**'
random_arr5 ** ones_arr2

array([[4., 7., 9., 8., 8.],
       [0., 8., 6., 8., 7.],
       [0., 7., 7., 2., 0.]])

In [45]:
# Do the same thing with np.square()
np.square(random_arr5)

array([[16, 49, 81, 64, 64],
       [ 0, 64, 36, 64, 49],
       [ 0, 49, 49,  4,  0]])

In [46]:
# Find the mean of the latest array using np.mean()
np.mean(random_arr5)

5.4

In [47]:
# Find the maximum of the latest array using np.max()
np.max(random_arr5)

9

In [48]:
# Find the minimum of the latest array using np.min()
np.min(random_arr5)

0

In [49]:
# Find the standard deviation of the latest array
np.std(random_arr5)

3.1790984046843636

In [50]:
# Find the variance of the latest array
np.var(random_arr5)

10.106666666666666

In [52]:
# Reshape the latest array to (3, 5, 1)
random_arr5.reshape(3,5,1)

array([[[4],
        [7],
        [9],
        [8],
        [8]],

       [[0],
        [8],
        [6],
        [8],
        [7]],

       [[0],
        [7],
        [7],
        [2],
        [0]]])

In [53]:
# Transpose the latest array
random_arr5.T

array([[4, 0, 0],
       [7, 8, 7],
       [9, 6, 7],
       [8, 8, 2],
       [8, 7, 0]])

What does the transpose do?

In [54]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_arr6 = np.random.randint(0,10, size=(3,3))
random_arr6

array([[7, 2, 2],
       [0, 4, 9],
       [6, 9, 8]])

In [55]:
random_arr7 = np.random.randint(0,10, size=(3,2))
random_arr7

array([[6, 8],
       [7, 1],
       [0, 6]])

In [56]:
# Perform a dot product on the two newest arrays you created
np.dot(random_arr6, random_arr7)

array([[ 56,  70],
       [ 28,  58],
       [ 99, 105]])

In [57]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_arr8 = np.random.randint(0,10, size=(4,3))
random_arr8

array([[6, 7, 4],
       [2, 7, 5],
       [2, 0, 2],
       [4, 2, 0]])

In [58]:
random_arr9 = np.random.randint(0,10, size=(4,3))
random_arr9

array([[4, 9, 6],
       [6, 8, 9],
       [9, 2, 6],
       [0, 3, 3]])

In [59]:
# Perform a dot product on the two newest arrays you created
np.dot(random_arr8, random_arr9)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [60]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random_arr8, random_arr9.T)

array([[111, 128,  92,  33],
       [101, 113,  62,  36],
       [ 20,  30,  30,   6],
       [ 34,  40,  40,   6]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [61]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_arr10 = np.random.randint(0,10, size=(4,3))
random_arr10

array([[4, 6, 6],
       [3, 6, 2],
       [5, 1, 9],
       [8, 4, 5]])

In [62]:
random_arr11 = np.random.randint(0,10, size=(4,3))
random_arr11

array([[3, 9, 6],
       [8, 6, 0],
       [0, 8, 8],
       [3, 8, 2]])

In [63]:
# Compare the two arrays with '>'
random_arr10 > random_arr11

array([[ True, False, False],
       [False, False,  True],
       [ True, False,  True],
       [ True, False,  True]])

What happens when you compare the arrays with `>`?

In [64]:
# Compare the two arrays with '>='
random_arr10 >= random_arr11

array([[ True, False,  True],
       [False,  True,  True],
       [ True, False,  True],
       [ True, False,  True]])

In [66]:
# Find which elements of the first array are greater than 7
random_arr10 > 7

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [ True, False, False]])

In [67]:
# Which parts of each array are equal? (try using '==')
random_arr10 == random_arr9

array([[ True, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [68]:
# Sort one of the arrays you just created in ascending order
np.sort(random_arr10)

array([[4, 6, 6],
       [2, 3, 6],
       [1, 5, 9],
       [4, 5, 8]])

In [69]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_arr10)

array([[0, 1, 2],
       [2, 0, 1],
       [1, 0, 2],
       [1, 2, 0]], dtype=int64)

In [70]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_arr10)

8

In [71]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_arr10)

7

In [73]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_arr10, axis=1)

array([1, 1, 2, 0], dtype=int64)

In [74]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(random_arr10, axis=0)

array([3, 0, 2], dtype=int64)

In [75]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 0.00511346, -0.23458713, -1.41537074, -0.42064532, -0.34271452],
       [-0.80227727, -0.16128571,  0.40405086,  1.8861859 ,  0.17457781],
       [ 0.25755039, -0.07444592, -1.91877122, -0.02651388,  0.06023021]])

In [76]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.